train:
  dataset: "ava"
  base_dir: "/home/ekim2/Storage/MetaProject/datasets/AVA_dataset/"
  data_csv: "345_ids.csv"
  nids: 16 # Number of identities to select
  devices: [0] # devices
  checkpoint: # checkpoint to resume training
  maxiter: 10_000_000
  init_learning_rate: 3.0e-4
  lr_scheduler_iter: 6000
  downsample: 4 # image downsampling factor at data loader
  num_workers: 4
  batchsize: 2 # Batch size per GPU to use
  clip: 1.0 # Gradient clipping
  losses:
    irgbl1: 1.0
    vertl1: 0.1
    kldiv: 1.0e-3 # 1.0e-3
    primvolsum: 0.01
  output_set: ["irgbrec", "sampledimg", "primscale"] 

progress:
  output_path: "run/" # output path where the progress is saved
  cross_id: True
  cross_id_n_subjects: 6

  tensorboard:
    log_freq: 10 # tensorboard logging frequency, in training iterations
    logdir: "log/" # dir where tensorboard log will output to