name: Python CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9"] #, "3.10", "3.11"]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install requirements via pip
        run: |
          python -m pip cache purge
          python -m pip install -r requirements.txt
      - name: build raymarcher
        path: extensions/mvpraymarch
        run: |
          make
      # - name: Run pytest
      #   run: |
      #     python -m pytest tests/